spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: pai
  freemarker:
    suffix: .ftl
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
  resources:
    static-locations: classpath:templates/,classpath:static/

server:
  port: 8090
  servlet:
    context-path: /

